module HazardUnit(
  input        clock,
  input        reset,
  input  [4:0] io_rs1_ex, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input  [4:0] io_rs2_ex, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input  [4:0] io_rd_mem, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input  [4:0] io_rd_wb, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input        io_reg_wr_enable_mem, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input        io_reg_wr_enable_wb, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  output [1:0] io_alu_rs1_src, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  output [1:0] io_alu_rs2_src, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input  [4:0] io_rs1_d, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input  [4:0] io_rs2_d, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input  [4:0] io_rd_ex, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input  [1:0] io_ex_regs_write_src, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  output       io_pc_stall, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  output       io_srFD_stall, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  output       io_srDE_flush, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  input        io_ex_jump_flag, // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
  output       io_srFD_flush // @[src/main/scala/riscv/core/HazardUnit.scala 7:14]
);
  wire  _io_alu_rs1_src_T_2 = io_rs1_ex != 5'h0; // @[src/main/scala/riscv/core/HazardUnit.scala 39:69]
  wire  _io_alu_rs1_src_T_3 = io_rs1_ex == io_rd_mem & io_reg_wr_enable_mem & io_rs1_ex != 5'h0; // @[src/main/scala/riscv/core/HazardUnit.scala 39:56]
  wire  _io_alu_rs1_src_T_7 = io_rs1_ex == io_rd_wb & io_reg_wr_enable_wb & _io_alu_rs1_src_T_2; // @[src/main/scala/riscv/core/HazardUnit.scala 42:56]
  wire [1:0] _io_alu_rs1_src_T_8 = _io_alu_rs1_src_T_7 ? 2'h2 : 2'h0; // @[src/main/scala/riscv/core/HazardUnit.scala 41:8]
  wire  _io_alu_rs2_src_T_2 = io_rs2_ex != 5'h0; // @[src/main/scala/riscv/core/HazardUnit.scala 50:69]
  wire  _io_alu_rs2_src_T_3 = io_rs2_ex == io_rd_mem & io_reg_wr_enable_mem & io_rs2_ex != 5'h0; // @[src/main/scala/riscv/core/HazardUnit.scala 50:56]
  wire  _io_alu_rs2_src_T_7 = io_rs2_ex == io_rd_wb & io_reg_wr_enable_wb & _io_alu_rs2_src_T_2; // @[src/main/scala/riscv/core/HazardUnit.scala 53:56]
  wire [1:0] _io_alu_rs2_src_T_8 = _io_alu_rs2_src_T_7 ? 2'h2 : 2'h0; // @[src/main/scala/riscv/core/HazardUnit.scala 52:8]
  wire  lw_stall = io_ex_regs_write_src[0] & (io_rs1_d == io_rd_ex | io_rs2_d == io_rd_ex); // @[src/main/scala/riscv/core/HazardUnit.scala 60:42]
  assign io_alu_rs1_src = _io_alu_rs1_src_T_3 ? 2'h1 : _io_alu_rs1_src_T_8; // @[src/main/scala/riscv/core/HazardUnit.scala 38:24]
  assign io_alu_rs2_src = _io_alu_rs2_src_T_3 ? 2'h1 : _io_alu_rs2_src_T_8; // @[src/main/scala/riscv/core/HazardUnit.scala 49:24]
  assign io_pc_stall = io_ex_regs_write_src[0] & (io_rs1_d == io_rd_ex | io_rs2_d == io_rd_ex); // @[src/main/scala/riscv/core/HazardUnit.scala 60:42]
  assign io_srFD_stall = io_ex_regs_write_src[0] & (io_rs1_d == io_rd_ex | io_rs2_d == io_rd_ex); // @[src/main/scala/riscv/core/HazardUnit.scala 60:42]
  assign io_srDE_flush = lw_stall | io_ex_jump_flag; // @[src/main/scala/riscv/core/HazardUnit.scala 64:29]
  assign io_srFD_flush = io_ex_jump_flag; // @[src/main/scala/riscv/core/HazardUnit.scala 66:17]
endmodule
